### ISSUE TITLE
Fix [GoodsSelector] 检查功能遗漏

### ISSUE THREAD

**Issue by liyuan-meng** [ShuyunFF2E/cloud-business#16]
1. 点击全部全选，然后切换到已选商品，无法移除（移除全部、移除当页）
  2. 如果全部全选数据量过大，点击移除按钮的时候，页面卡顿（需要 setTimeout 异步处理一下）
  3. 没有展开/折叠全部的功能
  4. 已选商品获取有问题（如果平台不限，那么获取已选商品不需要传商品ID，如果指定单个或多个平台，请求参数需要添加）
  5. 批量添加交互问题：批量添加一个或多个商品，添加成功后，点击全部商品 tab，商品列表应该找显示批量添加成功的一个或者多个商品（相当于搜索，搜索条件是多个商品ID）
  6. 表格下方的已选商品数量：按照原来的显示（原来的：300件；现在的：300/1000件，有的时候 1000那个数据还是错误的，并没有和总数相等）
  7. 根据是否支持 sku 判断是否显示 sku 相关搜索条件（sku 商家编码、sku 规格、商品编号（平台是京东显示商品编号、平台是其它显示 sku id））

目前测出来的有这些，太细节的还没看，比如 label 名称、placeholder 什么的最好和之前保持一致

**Comment by heriky** [comment]
第二条是表格渲染性能问题。
第四条不修复。
第六条的交互再跟产品经理讨论。

1、3、5、7条已修复。
