### ISSUE TITLE
[Editor] 内容编辑器问题整理

### ISSUE THREAD

**Issue by liyuan-meng** [ShuyunFF2E/cloud-business#35]
需要添加的配置
1. placeholder
2. style
3. keywords (需要支持使用独立的组件)

bug
1. 设置编辑器高度较小时，placeholder 被遮挡了（比如设置 height: 30px）
2. 设置编辑器高度较小时，如果没有输入内容，点击输入区域，没有显示光标（比如设置 height: 30px）

**Comment by silence717** [comment]
已在 0.0.14 版本中修复
